### ISSUE TITLE
WARNING: audio_to_images: No valid audio files were found error!

### ISSUE THREAD

**Issue by SepticDNB** [teticio/audio-diffusion#43]
I have a directory named dataSet contianing 4 MP3s and a WAV and I cant get past the 'no valid audio files' error.

The script seems to be seeing the files, I'm at a bit of a loss, running on Win10.

CMD log:

python scripts/audio_to_images.py ^
More?   --resolution 256,256 ^
More?   --input_dir dataSet ^
More?   --output_dir data
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 12.69it/s]
audio-diffusion\scripts\audio_to_images.py:64: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("No valid audio files were found.")
WARNING:audio_to_images:No valid audio files were found.

**Comment by teticio** [comment]
A bit difficult for me to debug from here. Can you do ¨dir dataSet¨ from the directory you are running the command from?

**Comment by hdparmar** [comment]
@SepticDNB I'm running into the same issue. Still debugging it. I can't find what's the catch here. But meanwhile, I use [Riffusion-manilab ](https://github.com/hdparmar/riffusion-manilab) to generate the spectrograms. 

Also, let me know if you manage to find what's happening! 

I think we meed to carefully check the mel functions.

**Comment by teticio** [comment]
It is possible that some library is needed for librosa to work. I have made a change so that the error is output (it will also give errors for any non audio files it finds that it is unable to load). Try pulling the latest version and running again. It should give a clue why it is not working for you. Sorry for the inconvenience, but "pip install librosa" isn't always enough - there is sometimes some extra setup involved and I hope the error message helps with that. Please include it here when you try it.
