### ISSUE TITLE
Question about Conditional Audio Generation Part

### ISSUE THREAD

**Issue by AlgernonLiu** [teticio/audio-diffusion#50]
Thank you for creating such an exciting project!
I have a small question regarding the Conditional Audio Generation section. I am interested in using image-encoded features as conditions to generate audio. Can the model be trained to input image representations to generate audio? I am unclear on how the Conditional Audio Generation section can be trained if I have the image-audio pairs and pre-trained image encoder. Could you please provide some explanation on this?
Thank you very much for your help!

**Comment by teticio** [comment]
Yes, that can be done. Currently, the example of conditional training I give uses an audio embedding (a mapping from 5 seconds of audio to a vector of 100 dimensions). You could use any vector obtained by any means. So, you would create a dataset with your audio samples together with images that you would like to represent those samples somehow. You would probably create some kind of embedding of those images, rather than giving the full pixel level features. How you would do this is another question - perhaps the images represent mood in some sense, so you could try to train a neural network to predict the genre of an audio given the accompanying image - this would then provide you with a way to represent or embed the images. Once you have this embedding, you can use it instead of the audio embedding.

**Comment by AlgernonLiu** [comment]
Thank you for your detailed advice! I will try!
